spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dosw_library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

jwt:
  secret: dG9kb3NMb3NTZWNyZXRvc1NvbkJhc2U2NEVuY29kZWRLZXlGb3JKV1QyMDI1
  expiration: 86400000

server:
  port: 8080
